# Generated by Django 4.0.5 on 2022-08-05 14:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('people', '0001_initial'),
        ('app_config', '0001_initial'),
    ]

    operations = []