# Generated by Django 4.0.5 on 2022-08-04 12:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ecommerce_category_id', models.CharField(blank=True, max_length=255, null=True)),
                ('last_modified', models.DateTimeField()),
                ('deleted', models.IntegerField()),
                ('hide_from_grid', models.IntegerField()),
                ('name', models.CharField(max_length=255)),
                ('color', models.TextField(blank=True, null=True)),
                ('system_category', models.BooleanField(default=False)),
                ('exclude_from_e_commerce', models.IntegerField()),
                ('category_info_popup', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'phppos_categories',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('trans_id', models.AutoField(primary_key=True, serialize=False)),
                ('trans_date', models.DateTimeField()),
                ('trans_comment', models.TextField()),
                ('trans_inventory', models.DecimalField(decimal_places=2, max_digits=15)),
            ],
            options={
                'db_table': 'phppos_inventory',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ItemImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('alt_text', models.CharField(max_length=255)),
                ('ecommerce_image_id', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'phppos_item_images',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ItemKits',
            fields=[
                ('item_kit_id', models.AutoField(primary_key=True, serialize=False)),
                ('item_kit_number', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('category', models.CharField(max_length=255)),
                ('unit_price', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('cost_price', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('deleted', models.IntegerField()),
            ],
            options={
                'db_table': 'phppos_item_kits',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Items',
            fields=[
                ('name', models.CharField(max_length=255)),
                ('item_number', models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='UPC/EAN/ISBN/SKU')),
                ('product_id', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('ecommerce_product_id', models.CharField(blank=True, max_length=255, null=True)),
                ('ecommerce_product_quantity', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField()),
                ('size', models.CharField(max_length=255)),
                ('tax_included', models.BooleanField(default=True)),
                ('cost_price', models.DecimalField(decimal_places=10, max_digits=23)),
                ('unit_price', models.DecimalField(decimal_places=10, max_digits=23)),
                ('promo_price', models.DecimalField(blank=True, decimal_places=10, max_digits=23, null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('reorder_level', models.DecimalField(blank=True, decimal_places=10, max_digits=23, null=True)),
                ('expire_days', models.BooleanField(default=False)),
                ('item_id', models.AutoField(primary_key=True, serialize=False)),
                ('allow_alt_description', models.BooleanField(default=True)),
                ('is_serialized', models.BooleanField(default=True)),
                ('override_default_tax', models.BooleanField(default=True)),
                ('is_ecommerce', models.BooleanField(default=True)),
                ('is_service', models.BooleanField(default=True)),
                ('is_ebt_item', models.BooleanField(default=True)),
                ('commission_percent', models.DecimalField(blank=True, decimal_places=10, max_digits=23, null=True)),
                ('commission_percent_type', models.CharField(blank=True, max_length=255, null=True)),
                ('commission_fixed', models.DecimalField(blank=True, decimal_places=10, max_digits=23, null=True)),
                ('change_cost_price', models.BooleanField(default=True)),
                ('disable_loyalty', models.BooleanField(default=True)),
                ('deleted', models.BooleanField(default=True)),
                ('last_modified', models.DateTimeField()),
                ('ecommerce_last_modified', models.DateTimeField(blank=True, null=True)),
                ('replenish_level', models.DecimalField(blank=True, decimal_places=10, max_digits=23, null=True)),
                ('system_item', models.BooleanField(default=True)),
                ('max_discount_percent', models.DecimalField(blank=True, decimal_places=3, max_digits=15, null=True)),
                ('max_edit_price', models.DecimalField(blank=True, decimal_places=10, max_digits=23, null=True)),
                ('min_edit_price', models.DecimalField(blank=True, decimal_places=10, max_digits=23, null=True)),
                ('required_age', models.BooleanField(default=False)),
                ('verify_age', models.BooleanField(default=False)),
                ('weight', models.DecimalField(blank=True, decimal_places=10, max_digits=23, null=True)),
                ('length', models.DecimalField(blank=True, decimal_places=10, max_digits=23, null=True)),
                ('width', models.DecimalField(blank=True, decimal_places=10, max_digits=23, null=True)),
                ('height', models.DecimalField(blank=True, decimal_places=10, max_digits=23, null=True)),
                ('ecommerce_shipping_class_id', models.CharField(blank=True, max_length=255, null=True)),
                ('long_description', models.TextField()),
                ('allow_price_override_regardless_of_permissions', models.BooleanField(default=False)),
                ('only_integer', models.BooleanField(default=True)),
                ('is_series_package', models.BooleanField(default=True)),
                ('series_quantity', models.BooleanField(default=False)),
                ('series_days_to_use_within', models.BooleanField(default=False)),
                ('is_barcoded', models.BooleanField(default=True)),
                ('default_quantity', models.DecimalField(blank=True, decimal_places=10, max_digits=23, null=True)),
                ('disable_from_price_rules', models.BooleanField(default=False)),
                ('last_edited', models.DateTimeField(blank=True, null=True)),
                ('info_popup', models.TextField(blank=True, null=True)),
                ('item_inactive', models.BooleanField(default=False)),
                ('barcode_name', models.CharField(max_length=255)),
                ('tags', models.CharField(blank=True, max_length=255, null=True)),
                ('is_favorite', models.BooleanField(default=False)),
                ('loyalty_multiplier', models.DecimalField(blank=True, decimal_places=10, max_digits=23, null=True)),
                ('ecommerce_inventory_item_id', models.CharField(blank=True, max_length=255, null=True)),
                ('weight_unit', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'Item',
                'verbose_name_plural': 'Items',
                'db_table': 'phppos_items',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ItemVariations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ecommerce_variation_id', models.CharField(blank=True, max_length=255, null=True)),
                ('ecommerce_variation_quantity', models.CharField(blank=True, max_length=255, null=True)),
                ('deleted', models.IntegerField()),
                ('reorder_level', models.DecimalField(blank=True, decimal_places=10, max_digits=23, null=True)),
                ('replenish_level', models.DecimalField(blank=True, decimal_places=10, max_digits=23, null=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('item_number', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('unit_price', models.DecimalField(blank=True, decimal_places=10, max_digits=23, null=True)),
                ('cost_price', models.DecimalField(blank=True, decimal_places=10, max_digits=23, null=True)),
                ('promo_price', models.DecimalField(blank=True, decimal_places=10, max_digits=23, null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('last_modified', models.DateTimeField()),
                ('ecommerce_last_modified', models.DateTimeField(blank=True, null=True)),
                ('is_ecommerce', models.IntegerField()),
                ('ecommerce_inventory_item_id', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'phppos_item_variations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Receivings',
            fields=[
                ('receiving_time', models.DateTimeField()),
                ('comment', models.TextField()),
                ('receiving_id', models.AutoField(primary_key=True, serialize=False)),
                ('payment_type', models.CharField(blank=True, max_length=255, null=True)),
                ('deleted', models.IntegerField()),
            ],
            options={
                'db_table': 'phppos_receivings',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ItemKitItems',
            fields=[
                ('item_kit', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='inventory.itemkits')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=15)),
            ],
            options={
                'db_table': 'phppos_item_kit_items',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ItemKitsTaxes',
            fields=[
                ('item_kit', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='inventory.itemkits')),
                ('name', models.CharField(max_length=255)),
                ('percent', models.DecimalField(decimal_places=3, max_digits=15)),
                ('cumulative', models.IntegerField()),
            ],
            options={
                'db_table': 'phppos_item_kits_taxes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ItemsTaxes',
            fields=[
                ('item', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='inventory.items')),
                ('name', models.CharField(max_length=255)),
                ('percent', models.DecimalField(decimal_places=3, max_digits=15)),
                ('cumulative', models.IntegerField()),
            ],
            options={
                'db_table': 'phppos_items_taxes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ReceivingsItems',
            fields=[
                ('receiving', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='inventory.receivings')),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('serialnumber', models.CharField(blank=True, max_length=255, null=True)),
                ('line', models.IntegerField()),
                ('quantity_purchased', models.IntegerField()),
                ('item_cost_price', models.DecimalField(decimal_places=2, max_digits=15)),
                ('item_unit_price', models.DecimalField(decimal_places=2, max_digits=15)),
                ('discount_percent', models.IntegerField()),
            ],
            options={
                'db_table': 'phppos_receivings_items',
                'managed': False,
            },
        ),
    ]
