# Generated by Django 4.0.5 on 2022-08-05 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='long_description',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
