# Generated by Django 4.0.5 on 2022-08-05 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_alter_items_description_alter_items_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='items',
            name='long_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='items',
            name='size',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
