# Generated by Django 4.0.5 on 2022-08-04 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_number', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('company_name', models.CharField(max_length=255)),
                ('taxable', models.IntegerField()),
                ('deleted', models.IntegerField()),
            ],
            options={
                'db_table': 'phppos_customers',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Employees',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('deleted', models.IntegerField()),
            ],
            options={
                'db_table': 'phppos_employees',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Manufacturers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.IntegerField()),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'phppos_manufacturers',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Suppliers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=255)),
                ('account_number', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('override_default_tax', models.IntegerField()),
                ('balance', models.DecimalField(decimal_places=10, max_digits=23)),
                ('deleted', models.IntegerField()),
                ('custom_field_1_value', models.CharField(blank=True, max_length=255, null=True)),
                ('custom_field_2_value', models.CharField(blank=True, max_length=255, null=True)),
                ('custom_field_3_value', models.CharField(blank=True, max_length=255, null=True)),
                ('custom_field_4_value', models.CharField(blank=True, max_length=255, null=True)),
                ('custom_field_5_value', models.CharField(blank=True, max_length=255, null=True)),
                ('custom_field_6_value', models.CharField(blank=True, max_length=255, null=True)),
                ('custom_field_7_value', models.CharField(blank=True, max_length=255, null=True)),
                ('custom_field_8_value', models.CharField(blank=True, max_length=255, null=True)),
                ('custom_field_9_value', models.CharField(blank=True, max_length=255, null=True)),
                ('custom_field_10_value', models.CharField(blank=True, max_length=255, null=True)),
                ('internal_notes', models.TextField(blank=True, null=True)),
                ('default_term_id', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'phppos_suppliers',
                'managed': False,
            },
        ),
    ]
