version: "3"

services:
  db:
    build:
      context: db
      dockerfile: Dockerfile
    volumes:
      - mysql_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: phppos
      MYSQL_USER: app_database_user
      MYSQL_PASSWORD: app_database_password
    networks:
      - network

  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin
    ports:
      - "4040:80"
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: password
    networks:
      - network

  django_pos:
    build: ./djangoPOS
    command: sh -c "python manage.py migrate; python manage.py runserver 0.0.0.0:5005"
    container_name: django-pos
    volumes:
      - ./djangoPOS/:/usr/src/app/
      - ./uploads:/uploads
    ports:
      - 5005:5005
    depends_on:
      - db
    networks:
      - network

networks:
  network:
volumes:
  mysql_data:
