# Generated by Django 4.0.5 on 2022-08-05 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app_config', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppConfig',
            fields=[
                ('key', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('value', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'pos_app_config',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AppFiles',
            fields=[
                ('file_id', models.AutoField(primary_key=True, serialize=False)),
                ('file_name', models.CharField(max_length=255)),
                ('file_data', models.TextField()),
                ('timestamp', models.DateTimeField()),
                ('expires', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'pos_app_files',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TaxClasses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField()),
                ('deleted', models.IntegerField()),
                ('name', models.CharField(max_length=255)),
                ('ecommerce_tax_class_id', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'pos_tax_classes',
                'managed': False,
            },
        ),
    ]
