# Generated by Django 4.0.5 on 2022-08-04 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='locations',
            options={'managed': False},
        ),
    ]
